# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SeattleParksGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeattleParksGame
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'FontAwesomeKit', '~> 2.2.0'
end
